# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Database Categories
    weight: 20
    identifier: dbcat
  - name: Data science
    PageRef: course/data-science/_index.md
    weight: 10
    parent: dbcat
  - name: Robotics
    PageRef: course/robotics/_index.md
    weight: 20
    parent: dbcat
  - name: About us
    PageRef: contact/index.md
    weight: 30
    identifier: aboutus
  - name: Team
    PageRef: course/data-science/_index.md
    weight: 10
    parent: aboutus
  - name: HEADS @ FMUP
    PageRef: course/robotics/_index.md
    weight: 20
    parent: aboutus
